- hosts: localhost
  tasks:
  - name: Install git
    yum: name=git state=latest 
    #sudo: yes
    become: yes
    become_method: sudo
  - name: Clone myrepo
    git: repo=https://github.com/yshapira/myrepo.git update=no
         dest=~/myfiles/myrepo
  - name: Clone spring-petclinic
    git: repo=https://github.com/yshapira/spring-petclinic.git
         dest=~/myfiles/spring-petclinic
  - name: Unarchive maven
    unarchive: src="http://apache.spd.co.il/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz"  dest=~/maven copy=no
  - name: set env param M2_HOME
    lineinfile: dest=~/.bash_profile regexp="^M2_HOME=" line="M2_HOME=~/maven" insertbefore="^PATH="
  - name: export env param M2_HOME
    lineinfile: dest=~/.bash_profile regexp="^M2_HOME" line="export M2_HOME" insertafter="^M2_HOME="
  - name: set env param M2
    lineinfile: dest=~/.bash_profile regexp="^M2" insertafter="^M2_HOME" line="M2=$M2_HOME/bin"
  - name: export env param M2
    lineinfile: dest=~/.bash_profile regexp="^M2_HOME" line="export M2" insertafter="^M2="
  - name: Add M2 to PATH
    lineinfile: dest=~/.bash_profile regexp="^PATH=.*:$M2" insertafter="^PATH=" line="PATH=$PATH:$M2"
  - name: Install docker
    yum: name=docker state=latest
    become: yes
    become_method: sudo
  - name: Add docker group to ec2-user
    user: append=yes groups=docker name=ec2-user
    become: yes
    become_method: sudo
  - name: start Docker Service
    service: name=docker state=started
    become: yes
    become_method: sudo

